'use strict';
const {check,eq,ok}=require('./harness.js'),D=require('../../hm-data.js');
const cid='c:ט:3',other='c:י:1',policy={cid,period:'Q1',from:'2026-09-01',to:'2026-12-31',tests:[{id:'push',rule:{target:40,step:5,points:5,min:0,max:100,rounding:'ceil'}},{id:'r60'}],exemptions:[]};
const seed={lang:'en','schema.version':D.SCHEMA_VERSION,'grades.periods':['Q1'],'ft.classes':{[cid]:{id:cid,name:'Grade 9',grade:'ט',num:3},[other]:{id:other,name:'Grade 10',grade:'י',num:1}},'stu.list':[{id:'a',cid,cls:'Grade 9',name:'Same',tests:[],grades:{Q1:{part:80,finalOverride:{value:87,note:'Teacher'}}}},{id:'b',cid,cls:'Grade 9',name:'Same',tests:[]},{id:'c',cid:other,cls:'Grade 10',name:'Other',tests:[]}],'ft.results':[{id:'old',sid:'a',cid,cls:'Grade 9',name:'Same',test:'push',val:35,d:'2026-09-02',ts:1}],'assessment.policies':{version:1,policies:[policy]}};
const results=p=>p.evaluate(()=>window.HM.LS.get('ft.results'));
const input=(p,sid,test)=>p.locator('#ag-table tr[data-sid="'+sid+'"] input[data-test="'+test+'"]');
async function open(p,sid){await p.evaluate(({cid,sid})=>window.ASSESSMENT_REPORT.open(cid,sid,'Q1'),{cid,sid});await p.locator('#ar-grid').click();await p.locator('#ag-date').fill('2026-10-04');}
module.exports={title:'Dated assessment measurement grid',tests:[
check('multi-pupil/date save adds attempts, keeps old history and manual grades, survives reload and updates exports',seed,async p=>{
 await open(p);eq(await input(p,'a','push').inputValue(),'');await input(p,'a','push').fill('30');await input(p,'b','push').fill('0');await input(p,'b','r60').fill('9.25');await p.locator('#ag-save').click();const r=await results(p);eq(r.length,4);eq(r[0],seed['ft.results'][0]);eq(r.slice(1).map(x=>[x.sid,x.test,x.val,x.d]),[['a','push',30,'2026-10-04'],['b','push',0,'2026-10-04'],['b','r60',9.25,'2026-10-04']]);eq(await p.evaluate(()=>window.HM.LS.get('stu.list')),seed['stu.list']);
 await p.reload();eq(await results(p),r);await p.evaluate(cid=>window.ASSESSMENT_REPORT.open(cid,null,'Q1'),cid);const q=p.locator('#ar-quick tbody tr');eq(await q.nth(0).locator('td').nth(3).innerText(),'35');eq(await q.nth(2).locator('td').nth(3).innerText(),'0');
 const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#ar-xlsx').click()]);await download.saveAs('/tmp/pe-grid-report.xlsx');const [csv]=await Promise.all([p.waitForEvent('download'),p.locator('#ar-csv').click()]);await csv.saveAs('/tmp/pe-grid-report.csv');await p.locator('#ar-grid').click();eq(await input(p,'a','push').inputValue(),'');await p.locator('#ag-save').click();ok((await p.locator('#ag-error').innerText()).includes('No new'));eq((await results(p)).length,4);
}),
check('date range, fractional counts and zero times reject a whole batch while zero repetitions save',seed,async p=>{
 await open(p);await input(p,'a','push').fill('10');await p.locator('#ag-date').fill('2027-01-01');await p.locator('#ag-save').click();ok((await p.locator('#ag-error').innerText()).includes('date'));await p.locator('#ag-date').fill('2026-09-01');await input(p,'b','r60').fill('0');await p.locator('#ag-save').click();eq(await results(p),seed['ft.results']);await input(p,'b','r60').fill('9.123');await p.locator('#ag-save').click();eq(await results(p),seed['ft.results']);await input(p,'b','r60').fill('');await input(p,'a','push').fill('1.5');await p.locator('#ag-save').click();eq(await results(p),seed['ft.results']);await input(p,'a','push').fill('0');await p.locator('#ag-save').click();eq((await results(p))[1].val,0);eq((await results(p))[1].d,'2026-09-01');
}),
{...check('actual quota failure preserves full history and all draft cells; retry succeeds once',seed,async p=>{
 await open(p);await input(p,'a','push').fill('41');await p.evaluate(()=>{window.__realSet=localStorage.setItem.bind(localStorage);localStorage.setItem=(k,v)=>{if(k==='peultimate.ft.results')throw new DOMException('Quota','QuotaExceededError');return window.__realSet(k,v);};});await p.locator('#ag-save').click();eq(await results(p),seed['ft.results']);eq(await input(p,'a','push').inputValue(),'41');ok((await p.locator('#ag-error').innerText()).includes('failed'));await p.evaluate(()=>localStorage.setItem=window.__realSet);await p.locator('#ag-save').click();eq((await results(p)).length,2);
}),allow:/\[אחסון\].*ft\.results/},
check('external measurement/policy changes and moved/duplicate pupils never receive stale entries',seed,async p=>{
 for(const mode of ['measurement','policy','move','duplicate']){
  await p.evaluate(s=>{for(const [k,v] of Object.entries(s))window.HM.LS.set(k,v);},seed);await open(p);await input(p,'a','push').fill('42');await p.evaluate(({mode,other})=>{const l=window.HM.LS;if(mode==='measurement')l.set('ft.results',l.get('ft.results').concat({id:'external',sid:'a',test:'push',val:20}));if(mode==='policy'){const v=l.get('assessment.policies');v.policies[0].to='2026-12-30';l.set('assessment.policies',v);}if(mode==='move'||mode==='duplicate'){const v=l.get('stu.list');if(mode==='move')v[0].cid=other;else v[2].id='a';l.set('stu.list',v);}},{mode,other});const before=await results(p);await p.locator('#ag-save').click();eq(await results(p),before);ok((await p.locator('#ag-error').innerText()).includes('changed'));await p.evaluate(()=>{window.HM.modal('ag-modal',false);document.getElementById('ag-modal').remove();});
 }
}),
check('period-exempt cells are disabled and no blank/exempt cells invent records', {...seed,'assessment.policies':{version:1,policies:[{...policy,exemptions:[{sid:'a',test:'push',reason:'Injury'}]}]}},async p=>{
 await open(p);ok(await input(p,'a','push').isDisabled());eq(await input(p,'a','push').getAttribute('title'),'Injury');await input(p,'b','push').fill('20');await p.locator('#ag-save').click();eq((await results(p)).slice(1).map(r=>r.sid),['b']);
}),
check('dirty Escape/Back/Close requires a choice and cancellation preserves all cells',seed,async p=>{
 await open(p);await input(p,'a','push').fill('42');await input(p,'a','push').press('Escape');await p.locator('#ask-no').click();eq(await input(p,'a','push').inputValue(),'42');await p.evaluate(()=>window.dispatchEvent(new PopStateEvent("popstate",{state:history.state})));await p.locator('#ask-no').click();await p.locator('#ag-close').click();await p.locator('#ask-ok').click();ok(await p.locator('#ar-modal').isVisible());eq(await results(p),seed['ft.results']);
}),
check('pupil report limits grid to one stable identity; corrupted outer data cannot open a writer',seed,async p=>{
 await open(p,'b');eq(await p.locator('#ag-table tbody tr').count(),1);ok(await input(p,'b','push').isVisible());await input(p,'b','push').fill('40');await p.locator('#ag-save').click();eq((await results(p))[1].sid,'b');await p.evaluate(cid=>{window.HM.LS.set('ft.results',{});window.ASSESSMENT_GRID.open(cid,'Q1');},cid);ok(!(await p.locator('#ag-modal').count()));eq(await results(p),{});
}),
check('full backup restore and simulated native mirror preserve appended results and grades', {...seed,__native:'android'},async p=>{
 await open(p);await input(p,'a','push').fill('0');await p.locator('#ag-save').click();const saved=await results(p);eq(await p.evaluate(async()=>{const h=window.HM,b=h.backupTest.snapshot();h.LS.set('ft.results',[]);return (await h.backupTest.apply(b)).failed;}),0);eq(await results(p),saved);await p.waitForFunction(()=>{const f=JSON.parse(localStorage.getItem('__fakefs')||'{}'),v=f['LIBRARY/pe-ultimate-data.json'];return v&&JSON.parse(JSON.parse(v).data['peultimate.ft.results']).length===2;});eq(await p.evaluate(()=>window.HM.LS.get('stu.list')[0].grades.Q1.finalOverride.value),87);
}),
check('five languages and phone/desktop grid retain labels, stable IDs and contained horizontal scrolling',seed,async p=>{
 for(const lang of ['en','he','ar','ru','es']){await p.evaluate(l=>window.I18N.set(l),lang);await p.setViewportSize({width:390,height:844});await open(p);ok((await p.locator('#ag-table').innerText()).includes('[a]'));ok((await p.locator('#ag-save').innerText()).length>5);ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await p.evaluate(()=>{window.HM.modal('ag-modal',false);document.getElementById('ag-modal').remove();});}
 await p.setViewportSize({width:1280,height:900});await open(p);await p.screenshot({path:'/tmp/pe-grid-desktop.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/pe-grid-phone.png'});
})
]};
