'use strict';
const {check,eq,ok}=require('./harness.js'),D=require('../../hm-data.js');
const cid='c:ט:3',policy={cid,period:'Q1',from:'2026-09-01',to:'2026-12-31',tests:[{id:'push'},{id:'r60'}],exemptions:[]};
const seed={lang:'en','schema.version':D.SCHEMA_VERSION,'grades.periods':['Q1'],'ft.classes':{[cid]:{id:cid,name:'Grade 9',grade:'ט',num:3}},'stu.list':[{id:'001',cid,cls:'Grade 9',name:'Same',tests:[],grades:{Q1:{part:80,finalOverride:{value:87,note:'Teacher'}}}},{id:'002',cid,cls:'Grade 9',name:'Same',tests:[]}],'ft.results':[{id:'old',sid:'001',cid,cls:'Grade 9',name:'Same',test:'push',val:35,d:'2026-09-02',ts:1}],'assessment.policies':{version:1,policies:[policy]}};
const text='sid\tname\tpush\tr60\n002\tSame\t0\t9,25\n001\tSame\t30\t';
const results=p=>p.evaluate(()=>window.HM.LS.get('ft.results'));
const input=(p,sid,test)=>p.locator('#ag-table tr[data-sid="'+sid+'"] input[data-test="'+test+'"]');
async function open(p,sid){await p.evaluate(({cid,sid})=>window.ASSESSMENT_REPORT.open(cid,sid,'Q1'),{cid,sid});await p.locator('#ar-grid').click();await p.locator('#ag-date').fill('2026-10-04');await p.locator('#ap-section summary').click();}
async function preview(p,value=text){await p.locator('#ap-text').fill(value);await p.locator('#ap-preview').click();}
module.exports={title:'Excel template and measurement paste preview',tests:[
check('offline actual Excel template has blank measurements; paste preview/apply only changes draft, then explicit save persists',seed,async p=>{
 await open(p);await p.context().setOffline(true);const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#ap-template').click()]);await download.saveAs('/tmp/pe-paste-template.xlsx');
 await preview(p);ok(await p.locator('#ap-apply').isVisible());eq(await p.locator('#ap-table tbody tr').count(),3);ok((await p.locator('#ap-result').innerText()).includes('2026-10-04'));eq(await results(p),seed['ft.results']);eq(await input(p,'002','push').inputValue(),'');await p.locator('#ap-apply').click();eq(await results(p),seed['ft.results']);eq(await input(p,'002','push').inputValue(),'0');eq(await input(p,'002','r60').inputValue(),'9.25');await p.locator('#ag-save').click();const saved=await results(p);eq(saved.length,4);eq(saved[0],seed['ft.results'][0]);eq(await p.evaluate(()=>window.HM.LS.get('stu.list')),seed['stu.list']);await p.reload();eq(await results(p),saved);
}),
check('blank pasted cells retain manual draft values; replacing a draft value requires confirmation',seed,async p=>{
 await open(p);await input(p,'001','push').fill('41');await input(p,'001','r60').fill('8.5');await preview(p,'sid\tname\tpush\tr60\n001\tSame\t30\t');await p.locator('#ap-apply').click();await p.locator('#ask-no').click();eq(await input(p,'001','push').inputValue(),'41');eq(await input(p,'001','r60').inputValue(),'8.5');await p.locator('#ap-apply').click();await p.locator('#ask-ok').click();eq(await input(p,'001','push').inputValue(),'30');eq(await input(p,'001','r60').inputValue(),'8.5');eq(await results(p),seed['ft.results']);
}),
check('bad header, duplicate/unknown IDs, formulae and invalid results reject the whole paste without changing any draft cell',seed,async p=>{
 await open(p);await input(p,'001','push').fill('41');
 for(const bad of ['sid\tname\tpush','sid\tname\tpush\tr60\n001\tSame\t30\t\n001\tSame\t20\t','sid\tname\tpush\tr60\n1\tSame\t30\t','sid\tname\tpush\tr60\n001\tSame\t30\t=9','sid\tname\tpush\tr60\n001\tSame\t30\t0','sid\tname\tpush\tr60\n001\tSame\t1.5\t']){await preview(p,bad);ok(!(await p.locator('#ap-apply').isVisible()));ok((await p.locator('#ap-error').innerText()).length>0);eq(await input(p,'001','push').inputValue(),'41');eq(await results(p),seed['ft.results']);}
}),
check('period exemption and pupil-only scope reject pasted measurements outside the editable selection', {...seed,'assessment.policies':{version:1,policies:[{...policy,exemptions:[{sid:'001',test:'push',reason:'Injury'}]}]}},async p=>{
 await open(p,'001');const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#ap-template').click()]);await download.saveAs('/tmp/pe-paste-pupil-template.xlsx');await preview(p);ok(!(await p.locator('#ap-apply').isVisible()));await preview(p,'sid\tname\tpush\tr60\n001\tSame\t0\t');ok((await p.locator('#ap-error').innerText()).includes('exemption'));eq(await results(p),seed['ft.results']);
}),
check('editing paste/date/draft invalidates preview; external changes also block apply',seed,async p=>{
 await open(p);await preview(p);await p.locator('#ag-date').fill('2026-10-05');await p.locator('#ap-apply').click();ok((await p.locator('#ap-error').innerText()).includes('changed'));eq(await input(p,'001','push').inputValue(),'');await p.locator('#ap-preview').click();await input(p,'001','push').fill('41');await p.locator('#ap-apply').click();ok((await p.locator('#ap-error').innerText()).includes('changed'));await p.locator('#ap-preview').click();await p.evaluate(()=>{const ls=window.HM.LS;ls.set('ft.results',ls.get('ft.results').concat({id:'external',sid:'001',test:'push',val:99}));});const before=await results(p);await p.locator('#ap-apply').click();await p.locator('#ask-ok').click();eq(await results(p),before);eq(await input(p,'001','push').inputValue(),'41');ok((await p.locator('#ap-error').innerText()).includes('changed'));
}),
check('save cannot discard unapplied paste or persist only the earlier manual draft',seed,async p=>{
 await open(p);await input(p,'001','push').fill('41');await p.locator('#ap-text').fill(text);await p.locator('#ag-save').click();ok((await p.locator('#ap-error').innerText()).includes('before saving'));eq(await results(p),seed['ft.results']);eq(await input(p,'001','push').inputValue(),'41');eq(await p.locator('#ap-text').inputValue(),text);await p.locator('#ap-text').fill('');await p.locator('#ag-save').click();eq((await results(p)).length,2);
}),
check('paste-only draft asks before discard and download failure preserves the paste',seed,async p=>{
 await open(p);await p.locator('#ap-text').fill(text);await p.locator('#ag-close').click();await p.locator('#ask-no').click();eq(await p.locator('#ap-text').inputValue(),text);await p.evaluate(()=>window.HMXlsx.workbook=()=>{throw new Error('Injected failure');});await p.locator('#ap-template').click();ok((await p.locator('#ap-error').innerText()).includes('failed'));eq(await p.locator('#ap-text').inputValue(),text);eq(await results(p),seed['ft.results']);
}),
{...check('save quota failure after paste retains editable values and original history; retry saves once',seed,async p=>{
 await open(p);await preview(p);await p.locator('#ap-apply').click();await p.evaluate(()=>{window.__set=localStorage.setItem.bind(localStorage);localStorage.setItem=(k,v)=>{if(k==='peultimate.ft.results')throw new DOMException('Quota','QuotaExceededError');return window.__set(k,v);};});await p.locator('#ag-save').click();eq(await results(p),seed['ft.results']);eq(await input(p,'002','push').inputValue(),'0');await p.evaluate(()=>localStorage.setItem=window.__set);await p.locator('#ag-save').click();eq((await results(p)).length,4);
}),allow:/\[אחסון\].*ft\.results/},
check('five languages, RTL and phone/desktop layouts expose paste controls without page overflow',seed,async p=>{
 for(const lang of ['he','en','ar','ru','es']){await p.evaluate(lang=>window.I18N.set(lang),lang);await open(p);await preview(p);ok(await p.locator('#ap-apply').isVisible());ok((await p.locator('#ap-table tbody tr').first().locator('td').nth(1).innerText()).length>4);const label=await p.locator('#ap-section summary').innerText();ok(!label.includes('ap.'));if(lang!=='he')ok(!/[\u0590-\u05FF]/.test(label));ok(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await p.evaluate(()=>{window.HM.modal('ag-modal',false);document.getElementById('ag-modal').remove();});}
 await p.evaluate(()=>window.I18N.set('he'));await p.setViewportSize({width:1280,height:900});await open(p);await preview(p);await p.screenshot({path:'/tmp/pe-paste-desktop.png'});await p.setViewportSize({width:390,height:844});ok(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await p.locator('#ap-result').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/pe-paste-phone.png'});
})]};
