'use strict';
const {check,eq,ok}=require('./harness.js'),D=require('../../hm-data.js'),fs=require('fs');
const cid='c:ט:3',other='c:י:1',today='2026-10-04';
const seed={lang:'en',__now:'2026-10-04T10:00:00','pf.guideSeen':true,'schema.version':D.SCHEMA_VERSION,'grades.periods':['Q1','Q2'],'grades.periodRanges':{Q1:{from:'2026-09-01',to:'2026-12-31'}},'ft.last':{grade:'ט',num:3,sort:'name'},'ft.classes':{[cid]:{id:cid,name:'ט׳3',grade:'ט',num:3,key:'ט3'},[other]:{id:other,name:'י׳1',grade:'י',num:1,key:'י1'}},'stu.list':[{id:'001',cid,cls:'ט׳3',name:'Same',sex:'boys',tests:[],grades:{Q1:{part:80},Q2:{part:60}}},{id:'002',cid,cls:'ט׳3',name:'Same',sex:'boys',tests:[],grades:{Q1:{part:70}}},{id:'003',cid:other,cls:'י׳1',name:'OTHER_PUPIL_SECRET',tests:[]}],'ft.results':[{id:'outside',sid:'001',cid,test:'push',val:999,d:'2026-08-31',ts:1}],'assessment.policies':{version:1,policies:[{cid,period:'Q1',from:'2026-09-01',to:'2026-12-31',tests:[{id:'push',rule:{target:40,step:5,points:5,min:0,max:100,rounding:'ceil'}},{id:'r60'}],exemptions:[]}]}};
const read=p=>p.evaluate(()=>{const l=window.HM.LS;return {results:l.get('ft.results'),pupils:l.get('stu.list'),policies:l.get('assessment.policies'),attendance:l.get('tools.att'),sessions:l.get('ls.sessions')};});
async function report(p,sid){await p.evaluate(({cid,sid})=>window.ASSESSMENT_REPORT.open(cid,sid,'Q1'),{cid,sid});}
async function download(p,button,path){
 if(await p.evaluate(()=>!!window.__cap)){
  const count=await p.evaluate(()=>window.__cap.filter(c=>c[0]==='Filesystem'&&c[1]==='writeFile'&&c[2].directory==='CACHE').length);
  await p.locator(button).click();await p.waitForFunction(count=>window.__cap.filter(c=>c[0]==='Filesystem'&&c[1]==='writeFile'&&c[2].directory==='CACHE').length>count,count);
  const data=await p.evaluate(()=>window.__cap.filter(c=>c[0]==='Filesystem'&&c[1]==='writeFile'&&c[2].directory==='CACHE').at(-1)[2].data);fs.writeFileSync(path,Buffer.from(data,'base64'));
 }else {const event=p.waitForEvent('download');await p.locator(button).click();await (await event).saveAs(path);}
}
async function journey(p,mode){
 await p.evaluate(()=>window.HM.go('ft'));await p.locator('#ft-startLesson').click();await p.waitForFunction(()=>!!window.HM.session.active());const session=await p.evaluate(()=>window.HM.session.active());eq(session.cid,cid);
 await p.evaluate(cid=>window.TOOLS.show(cid,'att'),cid);await p.locator('[data-att="001|p"]').click();await p.locator('[data-att="002|a"]').click();eq((await read(p)).attendance[today+'|ט׳3'],{'001':'p','002':'a'});
 await p.evaluate(()=>window.HM.go('ft'));await p.locator('#ft-tests [data-t="push"]').click();const count=p.locator('#ft-list [data-cnt]').first();await count.fill('40');await count.dispatchEvent('change');await p.waitForFunction(id=>window.HM.LS.get('ft.results').some(r=>r.sessionId===id),session.id);const measurement=(await read(p)).results.at(-1);eq(measurement.sid,'001');eq(measurement.val,40);eq(measurement.cid,cid);
 await p.reload();eq(await p.evaluate(()=>window.HM.session.active().id),session.id);eq((await read(p)).results.at(-1),measurement);await p.locator('#lsBarEnd').click();await p.locator('#end-go').click();await p.waitForFunction(()=>!window.HM.session.active());await p.waitForFunction(()=>document.body.dataset.mod==='cls');eq(await p.evaluate(id=>window.HM.session.list().find(s=>s.id===id).rating,session.id),null);
 await p.evaluate(cid=>window.ASSESSMENT.open(cid,'Q1','002'),cid);const exemption=p.locator('.as-ex-row[data-test="r60"]');await exemption.locator('.as-ex-check').check();await exemption.locator('.as-ex-reason').fill('MEDICAL_SECRET');await p.locator('#as-save').click();
 await report(p);await p.locator('#ar-grid').click();await p.locator('#ag-date').fill(today);await p.locator('#ap-section').evaluate(e=>e.open=true);await p.locator('#ap-text').fill('sid\tname\tpush\tr60\n001\tSame\t35\t8.5\n002\tSame\t0\t');await p.locator('#ap-preview').click();await p.locator('#ap-apply').click();await p.locator('#ap-apply').waitFor({state:'hidden'});ok(await p.locator('#ag-modal').isVisible());await p.locator('#ag-save').focus();await p.locator('#ag-save').press('Enter');const before=(await read(p));eq(before.results.length,5);eq(before.pupils,seed['stu.list']);
 await p.reload();await report(p);const rows=await p.locator('#ar-table tbody tr').evaluateAll(rs=>rs.map(r=>Array.from(r.cells,c=>c.textContent)));const item=(sid,test)=>rows.find(r=>r[1]===sid&&r[8]===test);eq(item('001','push')[12],'40');eq(item('002','push')[12],'0');eq(item('002','r60')[10],'Exempt');eq(item('001','push')[16],'100');
 await download(p,'#ar-csv','/tmp/pe-journey-'+mode+'.csv');await download(p,'#ar-xlsx','/tmp/pe-journey-'+mode+'.xlsx');await download(p,'#ar-historyCsv','/tmp/pe-journey-'+mode+'-history.csv');await p.locator('#ar-close').click();
 await p.evaluate(cid=>window.STU.show(cid,'grades'),cid);await p.locator('[data-final-edit="001"]').click();await p.locator('#gr-overrideValue').fill('86');await p.locator('#gr-overrideNote').fill('PRIVATE_TEACHER');await p.locator('#gr-overrideSave').click();const graded=await read(p);eq(graded.pupils[0].grades.Q1.finalOverride,{value:86,note:'PRIVATE_TEACHER'});eq(graded.pupils[0].grades.Q2,{part:60});eq(graded.pupils[1],seed['stu.list'][1]);eq(graded.results,before.results);
 await download(p,'#gr-csv','/tmp/pe-journey-'+mode+'-grades.csv');await download(p,'#gr-xlsx','/tmp/pe-journey-'+mode+'-grades.xlsx');
 await report(p,'001');await p.locator('#ar-studentPrint').click();await p.waitForFunction(()=>!document.getElementById('sp-html').disabled);await download(p,'#sp-html','/tmp/pe-journey-'+mode+'-pupil.html');const html=fs.readFileSync('/tmp/pe-journey-'+mode+'-pupil.html','utf8');for(const privateText of ['OTHER_PUPIL_SECRET','PRIVATE_TEACHER','MEDICAL_SECRET','999'])ok(!html.includes(privateText));await p.locator('#sp-close').click();await p.locator('#ar-close').click();
 const saved=await read(p);const restored=await p.evaluate(async()=>{const h=window.HM,s=await h.backupTest.snapshotFull();h.LS.set('ft.results',[]);h.LS.set('stu.list',[]);return h.backupTest.apply(s);});eq(restored.failed,0);await p.reload();eq(await read(p),saved);
 if(mode==='ios')await p.waitForFunction(()=>{const f=JSON.parse(localStorage.getItem('__fakefs')||'{}'),file=f['LIBRARY/pe-ultimate-data.json'];return file&&JSON.parse(JSON.parse(file).data['peultimate.stu.list'])[0]?.grades?.Q1?.finalOverride?.value===86;});
}
module.exports={title:'Cross-module field-to-PC journey',tests:[check('browser lesson → desktop assessment → grades/exports → pupil output → restore',seed,p=>journey(p,'web')),check('same journey with simulated iOS persistence bridge',{...seed,__native:'ios'},p=>journey(p,'ios'))]};
