"use strict";
const {run}=require("./harness.js");
const suites=[
  require("./transfer22.e2e.js"),
  require("./library21.e2e.js"),
  require("./gameadapt.e2e.js"),
  require("./builder19.e2e.js"),
  require("./fieldjourney.e2e.js"),
  require("./backuprestore.e2e.js"),
  require("./assessmentexemptions.e2e.js"),
  require("./finaloverride.e2e.js"),
  require("./assessmentgrid.e2e.js"),
  require("./assessmentpaste.e2e.js"),
  require("./studentreport.e2e.js"),
  require("./assessmentreport.e2e.js"),
  require("./assessmenteditor.e2e.js"),
  require("./persistenceharness.e2e.js"),
  require("./studentmissing.e2e.js"),
  require("./identity.e2e.js"),
  require("./storage.e2e.js"),
  require("./backup.e2e.js"),
  require("./classes.e2e.js"),
  require("./progress.e2e.js"),
  require("./corrective.e2e.js"),
  require("./session.e2e.js"),
  require("./profile.e2e.js"),
  require("./teach.e2e.js"),
  require("./identity8.e2e.js"),
  require("./rename9.e2e.js"),
  require("./coverage10.e2e.js"),
  require("./polish10_5.e2e.js"),
  require("./progress11.e2e.js"),
  require("./attendgrade12.e2e.js"),
  require("./pilotpolish13.e2e.js"),
  require("./info14.e2e.js"),
  require("./topbar.e2e.js"),
  require("./timing.e2e.js"),
  require("./lead.e2e.js"),
  require("./nav.e2e.js"),
  require("./update.e2e.js"),
  require("./today.e2e.js"),
  require("./lessonend.e2e.js"),
  require("./prevlesson21.e2e.js"),
  require("./week.e2e.js"),
  require("./groups.e2e.js"),
  require("./focus.e2e.js"),
  require("./reps.e2e.js"),
  require("./menu.e2e.js"),
  require("./rostersync.e2e.js"),
  require("./manual.e2e.js"),
  require("./i18n15.e2e.js"),
  require("./shell16.e2e.js"),
  require("./field17.e2e.js"),
  require("./hub18.e2e.js"),
  require("./prep19.e2e.js"),
  require("./field20.e2e.js"),
  require("./clean21.e2e.js"),
  require("./shell22.e2e.js"),
  require("./combined23.e2e.js"),
  require("./audit29.e2e.js"),
  require("./round3.e2e.js"),
  require("./native.e2e.js"),
  require("./lang30.e2e.js"),
  require("./stage1.e2e.js"),
  require("./stage2.e2e.js"),
  require("./lessonbank.e2e.js")
];
run(suites).then(fail=>{
  if(fail)return process.exit(1);
  // This probe serves real index.html/SW instead of the standalone harness.
  // Await its process and preserve failures; requiring it would not await it.
  const result=require("node:child_process").spawnSync(process.execPath,
    [...process.execArgv,require.resolve("../review/offline-lazy.e2e.js")],{stdio:"inherit"});
  if(result.error){ console.error(result.error); return process.exit(1); }
  process.exit(result.signal||result.status!==0?1:0);
})
  .catch(e=>{ console.error(e); process.exit(1); });
