'use strict';
const fs=require('fs'),{check,eq,ok}=require('./harness.js'),D=require('../../hm-data.js');
const cid='c:ט:3',other='c:י:1',policy={cid,period:'Q1',from:'2026-09-01',to:'2026-12-31',tests:[{id:'push'},{id:'r60'},{id:'situp'}],exemptions:[{sid:'a',test:'situp',reason:'MEDICAL_SECRET'}]};
const seed={lang:'en','schema.version':D.SCHEMA_VERSION,'grades.periods':['Q1'],'ft.classes':{[cid]:{id:cid,name:'Grade 9',grade:'ט',num:3},[other]:{id:other,name:'Grade 10',grade:'י',num:1}},'stu.list':[{id:'a',cid,cls:'Grade 9',name:'First pupil',tests:[],grades:{Q1:{part:80,finalOverride:{value:87,note:'PRIVATE_TEACHER'}}}},{id:'b',cid,cls:'Grade 9',name:'SECOND_PUPIL_SECRET',tests:[]},{id:'c',cid:other,cls:'Grade 10',name:'OTHER_CLASS_SECRET',tests:[]}],'ft.results':[{id:'old',sid:'a',cid,test:'push',val:35,d:'2026-09-02',ts:1},{id:'best',sid:'a',cid,test:'push',val:40,d:'2026-10-04',ts:2},{id:'outside',sid:'a',cid,test:'push',val:999,d:'2026-08-31',ts:0},{id:'zero',sid:'b',cid,test:'push',val:0,d:'2026-10-04',ts:3}],'assessment.policies':{version:1,policies:[policy]}};
const frame=p=>p.frameLocator('#sp-preview'),ready=p=>p.waitForFunction(()=>!document.getElementById('sp-html').disabled);
async function open(p,sid){await p.evaluate(({cid,sid})=>window.ASSESSMENT_REPORT.open(cid,sid,'Q1'),{cid,sid});await p.locator('#ar-studentPrint').click();if(sid)await ready(p);}
const stored=p=>p.evaluate(()=>JSON.stringify({pupils:window.HM.LS.get('stu.list'),results:window.HM.LS.get('ft.results'),policies:window.HM.LS.get('assessment.policies')}));
module.exports={title:'Teacher-reviewed personal progress print',tests:[
check('class report requires explicit pupil selection; offline downloaded HTML isolates pupil and prints as a real PDF',seed,async p=>{
 const before=await stored(p);await open(p);eq(await p.locator('#sp-pupil').inputValue(),'');ok(await p.locator('#sp-print').isDisabled());await p.locator('#sp-pupil').selectOption('a');await ready(p);await p.context().setOffline(true);const text=await frame(p).locator('body').innerText();ok(text.includes('First pupil'));ok(text.includes('40'));for(const secret of ['SECOND_PUPIL_SECRET','OTHER_CLASS_SECRET','PRIVATE_TEACHER','MEDICAL_SECRET','999'])ok(!text.includes(secret));
 const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#sp-html').click()]);await download.saveAs('/tmp/pe-pupil-progress.html');const html=fs.readFileSync('/tmp/pe-pupil-progress.html','utf8');ok(!/<script\b/i.test(html));ok(!html.includes('peultimate.'));ok(!html.includes('SECOND_PUPIL_SECRET'));const pdf=await p.context().newPage();await pdf.setContent(html);await pdf.pdf({path:'/tmp/pe-pupil-progress.pdf',format:'A4',printBackground:true});await pdf.close();eq(await stored(p),before);
}),
check('pupil context selects only that pupil; optional history stays period-scoped and print runs only after a click',seed,async p=>{
 await open(p,'a');eq(await p.locator('#sp-pupil option').count(),2);ok(!(await frame(p).locator('body').innerText()).includes('2026-09-02'));await p.locator('#sp-history').check();await ready(p);const text=await frame(p).locator('body').innerText();ok(text.includes('2026-09-02'));ok(!text.includes('999'));ok(!text.includes('MEDICAL_SECRET'));await p.evaluate(()=>{window.__prints=0;document.getElementById('sp-preview').contentWindow.print=()=>window.__prints++;});eq(await p.evaluate(()=>window.__prints),0);await p.locator('#sp-print').click();eq(await p.evaluate(()=>window.__prints),1);
}),
check('legitimate zero is shown while missing and exempt values are blank and reasons/grades never appear',seed,async p=>{
 await open(p,'b');const rows=frame(p).locator('table tbody tr');eq(await rows.nth(0).locator('td').nth(2).innerText(),'0');eq(await rows.nth(1).locator('td').nth(2).innerText(),'—');await p.locator('#sp-close').click();await open(p,'a');eq(await frame(p).locator('table tbody tr').nth(2).locator('td').nth(2).innerText(),'—');ok(!(await frame(p).locator('body').innerText()).includes('PRIVATE_TEACHER'));
}),
check('freshness and globally ambiguous IDs block output and clear the preview without storage writes',seed,async p=>{
 await open(p,'a');await p.evaluate(()=>{const l=window.HM.LS,v=l.get('stu.list');v[2].id='a';l.set('stu.list',v);});const before=await stored(p);await p.locator('#sp-html').click();ok((await p.locator('#sp-error').innerText()).includes('ambiguous'));ok(await p.locator('#sp-html').isDisabled());ok(!(await p.locator('#sp-preview').isVisible()));eq(await stored(p),before);await p.locator('#sp-close').click();await open(p);await p.locator('#sp-pupil').selectOption('a');ok(await p.locator('#sp-print').isDisabled());
}),
check('injected print/download failures preserve stored data and allow retry; Back returns to teacher report',seed,async p=>{
 const before=await stored(p);await open(p,'a');await p.evaluate(()=>document.getElementById('sp-preview').contentWindow.print=()=>{throw new Error('Injected print');});await p.locator('#sp-print').click();ok((await p.locator('#sp-error').innerText()).includes('failed'));await p.evaluate(()=>{window.__url=URL.createObjectURL;URL.createObjectURL=()=>{throw new Error('Injected download');};});await p.locator('#sp-html').click();ok((await p.locator('#sp-error').innerText()).includes('failed'));await p.evaluate(()=>URL.createObjectURL=window.__url);const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#sp-html').click()]);ok(download.suggestedFilename().endsWith('.html'));await p.evaluate(()=>window.dispatchEvent(new PopStateEvent('popstate',{state:history.state})));eq(await p.locator('#sp-modal').count(),0);ok(await p.locator('#ar-modal').isVisible());eq(await stored(p),before);
}),
check('escaped pupil text and sandbox/CSP make the preview and downloaded document inert', {...seed,'stu.list':[{...seed['stu.list'][0],name:'<img src=x onerror="window.HACKED=1">' },...seed['stu.list'].slice(1)]},async p=>{
 await open(p,'a');ok((await frame(p).locator('body').innerText()).includes('<img'));eq(await frame(p).locator('img').count(),0);eq(await p.evaluate(()=>window.HACKED||null),null);eq(await p.locator('#sp-preview').getAttribute('sandbox'),'allow-same-origin allow-modals');ok((await frame(p).locator('meta[http-equiv="Content-Security-Policy"]').getAttribute('content')).includes("script-src 'none'"));
}),
check('five languages and phone/desktop preview have labels, units and correct document direction',seed,async p=>{
 for(const lang of ['en','he','ar','ru','es']){await p.evaluate(l=>window.I18N.set(l),lang);await p.setViewportSize({width:390,height:844});await open(p,'a');const heading=await frame(p).locator('h1').innerText();ok(heading.length>5&&!heading.includes('sp.'));eq(await frame(p).locator('html').getAttribute('dir'),lang==='he'||lang==='ar'?'rtl':'ltr');ok((await frame(p).locator('tbody tr').first().locator('td').first().innerText()).length>3);ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await p.locator('#sp-close').click();}
 await p.evaluate(()=>window.I18N.set('he'));await p.setViewportSize({width:1280,height:900});await open(p,'a');await p.screenshot({path:'/tmp/pe-student-report-desktop.png'});await p.setViewportSize({width:390,height:844});await p.locator('#sp-preview').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/pe-student-report-phone.png'});
})]};
